---
- name: install bacula packages and postgresql
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - bacula-director
    - bacula-storage
    - bacula-console
    - postgresql-server
    - postgresql-contrib
    - python-psycopg2
    - libselinux-python
    - policycoreutils-python
  tags:
    - packages

- name: open firewall
  firewalld:
    service: bacula
    permanent: true
    state: enabled
  notify:
    - reload firewalld
  tags:
    - firewall
