---
# handlers file for bacula
- name: restart postgresql
  service:
    name: postgresql
    state: restarted

- name: restart bacula-dir
  service:
    name: bacula-dir
    state: restarted

- name: restart bacula-sd
  service:
    name: bacula-sd
    state: restarted

- name: reload firewalld
  service:
    name: firewalld
    state: restarted
